commitizen:
  major_version_zero: true
  name: cz_customize # 또는 cz_customizable로 변경해볼 수 있습니다
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.0.1
  version_scheme: pep440

  # 커밋 규칙 커스터마이징 설정
  customize:
    # 커밋 메시지 작성 시 사용자에게 표시할 질문
    questions:
      - type: select
        name: type
        message: "커밋 유형을 선택하세요:"
        choices:
          - value: feat
            name: "feat: 새로운 기능 추가"
          - value: fix
            name: "fix: 버그 수정"
          - value: docs
            name: "docs: 문서 수정"
          - value: style
            name: "style: 코드 포맷팅, 세미콜론 누락 등 (코드 변경 없음)"
          - value: refactor
            name: "refactor: 코드 리팩토링 (기능 변경 없음)"
          - value: test
            name: "test: 테스트 코드 추가/수정"
          - value: chore
            name: "chore: 빌드 관련 업무 수정 및 패키지 매니저 설정"
      - type: input
        name: subject
        message: "변경 사항을 간략히 설명하세요 (한글로):"
      - type: input
        name: body
        message: "자세한 설명을 입력하세요 (선택사항):"
      - type: input
        name: footer
        message: "관련 이슈 번호 (예: #123, 선택사항):"

    # 커밋 메시지 템플릿 정의
    message_template: |
      {{ type }}: {{ subject }}

      {{ body }}

      {{ footer }}
